(() => {
  const VERIFIED_AT = '21.08.2026';

  const verifiedGuideItems = [
    {category:'nature',kicker:'Direkt ab Kerschenbach',title:'Arnika-Route KB 3',text:'7-km-Rundtour entlang des Dürrbachs Richtung Kronenburg mit rund 127 Höhenmetern, Arnikawiese und schönen Blicken auf Kronenburg. Die offiziellen Quellen widersprechen sich bei der Einstufung „leicht/mittel“, deshalb zeigen wir bewusst keine Schwierigkeitsstufe.',meta:['7,0 km','ca. 1:50 h','127 hm'],url:'https://www.gerolsteiner-land.de/touren/kerschenbach-kb3'},
    {category:'nature',kicker:'Kerschenbach · KB2',title:'XXL-Bank Kerschenbach',text:'Große Aussichtsbank mit weitem Blick über die Landschaft und das Feriendorf. Sie liegt am örtlichen Rundwanderweg KB2.',meta:['Aussicht','KB2','kostenlos'],url:'https://www.gerolsteiner-land.de/pois/xxl-bank-kerschenbach'},
    {category:'nature',kicker:'Kerschenbach · familienfreundlich',title:'Wassererlebnisplatz',text:'Naturerlebnis direkt am Bach mit Schutzhütte. Der Bachzugang ist barrierefrei erreichbar und der Platz liegt an den Wanderwegen K1 und K2.',meta:['Kinder','Bach','K1 · K2'],url:'https://kerschenbach.de/wassererlebnisplatz-in-kerschenbach/'},
    {category:'nature',kicker:'Stadtkyll',title:'Kyllpark & Kyllradweg',text:'Kurpark an der Kyll für eine kleine Runde am Wasser und als guter Einstieg in die Umgebung von Stadtkyll.',meta:['Park','Wasser','Radweg'],url:'https://www.eifel.info/pois/kurpark-stadtkyll'},
    {category:'culture',kicker:'Historische Eifel',title:'Kronenburg',text:'Historischer Burgort mit alten Gassen, Burgresten und weitem Blick über die Eifellandschaft.',meta:['Burgort','Spaziergang','Ausflug'],url:'https://www.eifel.info/pois/kronenburg'},
    {category:'culture',kicker:'Birgel',title:'Historische Wassermühle',text:'Mühlen-Erlebniszentrum mit Getreide-, Säge-, Senf- und Ölmühle. Führungen und Gastronomie machen die Mühle auch bei wechselhaftem Wetter interessant.',meta:['Mühlen','Führung','Gastronomie'],url:'https://www.eifel.info/pois/historische-wassermuehle-birgel'},
    {category:'food',kicker:'Stadtkyll · Auelstraße 14–16',title:'Pizzeria La Sirena',text:'Mediterrane Küche mit Pizza, Pasta, Fisch- und Fleischgerichten. Aktuell mittwochs Ruhetag; an den übrigen Tagen mittags und abends geöffnet.',meta:['italienisch','Terrasse','06597 900623'],url:'https://www.eifel.info/gastro/pizzeria-la-sirena-stadtkyll'},
    {category:'food',kicker:'Stadtkyll · Wirftstraße 19',title:'Woodstock Food & Musik',text:'Erlebnisgastronomie mit Lavasteingrill, Tapas und Musik-Ambiente im früheren Balkan Land.',meta:['Lavastein','Tapas','06597 900538'],url:'https://www.gerolsteiner-land.de/gastro/hotel-restaurant-balkan-land'},
    {category:'food',kicker:'Stadtkyll · Wirftstausee',title:'Bistro am See',text:'Unkomplizierte Einkehr in der Tennishalle am Wirftstausee mit regionaler Küche und Hausmannskost. Aktuell Montag bis Freitag ab 17 Uhr.',meta:['regional','Bistro','06597 9029606'],url:'https://www.eifel.info/gastro/stadtkyll-bistro-am-see'},
    {category:'food',kicker:'Dahlem-Kronenburg',title:'Restaurant Villa Kronenburg',text:'Restaurant mit großer Gartenterrasse, regionalem Angebot, vegetarischen Optionen sowie Café/Crêperie am Tag.',meta:['regional','vegetarisch','Terrasse'],url:'https://www.eifel.info/gastro/restaurant-villa-kronenburg'},
    {category:'food',kicker:'Stadtkyll · Raiffeisenplatz 3',title:'Café Doppelfeld',text:'Bäckerei, Café und Eisdiele mit selbst angesetztem Sauerteig und Eis nach italienischem Originalrezept. Aktuelle Öffnungszeiten bitte vor dem Besuch über die verlinkte Tourismusseite prüfen.',meta:['Bäckerei','Café','06597 4973'],url:'https://www.eifel.info/gastro/cafe-conditorei-baeckerei-doppelfeld'},
    {category:'service',kicker:'Einkaufen · Stadtkyll',title:'REWE Stadtkyll',text:'Vollsortimenter in Stadtkyll, Im Hahnborn 5. Aktuell Montag bis Samstag von 07:00 bis 22:00 Uhr geöffnet.',meta:['Im Hahnborn 5','07–22 Uhr','06597 2990'],url:'https://www.rewe.de/marktseite/stadtkyll/1765219/rewe-markt-im-hahnborn-5'},
    {category:'service',kicker:'Gesundheit · Stadtkyll',title:'Marien-Apotheke',text:'Hauptstraße 25. Aktuell Montag bis Freitag 08:30–19:00 Uhr und Samstag 08:30–13:00 Uhr. Die Apotheke bietet unter anderem Vorbestellung und Botendienst.',meta:['Hauptstr. 25','06597 2319','Apotheke'],url:'https://www.apotheke-stadtkyll.de/'},
    {category:'service',kicker:'Gesundheit · Stadtkyll',title:'Ärztliche Versorgung',text:'Gemeinschaftspraxen in der Kurallee 8 (06597 3609) und Schwammertstraße 3 (06597 2425). Außerhalb der Sprechzeiten hilft der ärztliche Bereitschaftsdienst unter 116117.',meta:['2 Praxen','116117','Stadtkyll'],url:'https://www.stadtkyll.de/wohnen/gesundheit/aerzte/'},
    {category:'service',kicker:'Kerschenbach · Gemeindehaus',title:'E-Auto laden',text:'Am Gemeindehaus stehen zwei Ladestationen für E-Autos. Die Bedienung wird am Display erklärt; für die Bezahlung ist eine App erforderlich. Vor Ort steht dafür auch das freie WLAN der Ortsgemeinde zur Verfügung.',meta:['2 Ladepunkte','Gemeindehaus','Free WiFi'],url:'https://kerschenbach.de/aktuelles/?e-page-baf20b0=2'},
    {category:'service',kicker:'Vor Ort · Stadtkyll',title:'Tourist-Information',text:'Beratung, Wander- und Radkarten sowie aktuelle Ausflugstipps im Bahnhofsgebäude. Mo–Fr 09:00–16:30 Uhr, April–Oktober zusätzlich Sa 09:00–13:00 Uhr.',meta:['Burgberg 22','06591 13-3200','Tourist-Info'],url:'https://www.eifel.info/pois/tourist-information-oberes-kylltal'}
  ];

  const stayDining = [
    {place:'Stadtkyll',title:'Pizzeria La Sirena',text:'Italienische und mediterrane Küche mit Pizza, Pasta, Fisch, Fleisch und Desserts.',image:'https://www.eifel.info/images/ka_H2uz6ZMM/rs:fill:2560:0/cb:/g:ce/aHR0cHM6Ly9yZXNjLmRlc2tsaW5lLm5ldC9pbWFnZXMvUlBULzEvNzgwNWYxZDktZGQ4Zi00MGE3LWExMDItZGM5MjVkZjFlMjdiLzk5L2ltYWdlLmpwZw',url:'https://www.eifel.info/gastro/pizzeria-la-sirena-stadtkyll',tag:'Italienisch'},
    {place:'Stadtkyll',title:'Woodstock Food & Musik',text:'Tapas, Lavasteingrill und Musik-Ambiente im neu aufgestellten ehemaligen Balkan Land.',image:'https://www.gerolsteiner-land.de/images/FYZJoPlPWBE/rs:fill:2560:0/cb:/g:ce/aHR0cHM6Ly9yZXNjLmRlc2tsaW5lLm5ldC9pbWFnZXMvUlBULzEvNzIzYTI1YTktYWU0Ny00ZTA5LWFkNGYtN2E2OThlNDhjNmU4Lzk5L2ltYWdlLmpwZw',url:'https://www.gerolsteiner-land.de/gastro/hotel-restaurant-balkan-land',tag:'Erlebnisgastronomie'},
    {place:'Stadtkyll · Wirftstausee',title:'Bistro am See',text:'Lockeres Bistro an der Tennishalle beim Wirftstausee – für einen Happen, Hausmannskost oder einen kleinen Absacker.',image:'https://www.eifel.info/images/0qNThWa4M98/rs:fill:2560:0/cb:/g:ce/aHR0cHM6Ly9yZXNjLmRlc2tsaW5lLm5ldC9pbWFnZXMvUlBULzEvYWJiMWM5ZTMtNmFjYi00OGY5LTkzNDAtZjhhOTY5NDBlNWM0Lzk5L2ltYWdlLmpwZw',url:'https://www.eifel.info/gastro/stadtkyll-bistro-am-see',tag:'Regional'},
    {place:'Blankenheim-Ripsdorf',title:'Restaurant Breuer',text:'Klassisches Restaurant und Hotel mit regionaler Küche, Tagesgerichten und Biergarten.',image:'https://www.breuer-ripsdorf.de/Breuer_Ripsdorf/Willkommen_files/hotel-biergarten_600.jpg',url:'https://www.breuer-ripsdorf.de/',tag:'Ausflugslokal'},
    {place:'Kronenburg',title:'Restaurant Villa Kronenburg',text:'Regionale Küche, vegetarische Optionen und eine große Gartenterrasse im historischen Burgort.',image:'https://www.eifel.info/images/7Oibiw43GFk/rs:fill:2560:0/cb:/g:ce/aHR0cHM6Ly9yZXNjLmRlc2tsaW5lLm5ldC9pbWFnZXMvUlBULzEvZTljZWNiZGQtM2M3Zi00OGM2LWE2NjMtNWU0ZWFjZTYwYTllLzk5L2ltYWdlLmpwZw',url:'https://www.eifel.info/gastro/restaurant-villa-kronenburg',tag:'Terrasse'},
    {place:'Birgel',title:'Historische Wassermühle Birgel',text:'Mühlen-Erlebniszentrum mit Gastronomie und Biergarten – Essen lässt sich hier gut mit einem Ausflug verbinden.',image:'https://www.urlaub-in-rheinland-pfalz.de/domizil-390/73528/Historische_Wassermuehle_Birgel.webp',url:'https://www.eifel.info/pois/historische-wassermuehle-birgel',tag:'Erlebnis & Essen'},
    {place:'Birgel',title:'Hotel-Restaurant Birgeler Hof',text:'Gutbürgerliche Küche, regionale Gerichte, Moselwein und Biergarten.',image:'https://www.eifel.info/images/_shZLf_nIAc/rs:fill:2560:0/cb:/g:ce/aHR0cHM6Ly9yZXNjLmRlc2tsaW5lLm5ldC9pbWFnZXMvUlBULzEvMzM3YmZiMjMtZGIzMi00MTczLWExZmUtMDM3MzgwNzIwNDU2Lzk5L2ltYWdlLmpwZw',url:'https://www.birgelerhof.de/restaurant/',tag:'Gutbürgerlich'},
    {place:'Olzheim',title:'Hotel Feldmaus',text:'Deutsch-französische Abendküche im Landhotel; aktuelle Speisekarte und Öffnungstage werden auf der eigenen Website gepflegt.',image:'https://static.wixstatic.com/media/9b6f19_774e5f869e8c48b99ed236006d89e65f%7Emv2.jpg/v1/fit/w_2500,h_1330,al_c/9b6f19_774e5f869e8c48b99ed236006d89e65f%7Emv2.jpg',url:'https://www.feldmaus.de/restaurant',tag:'Deutsch-französisch'}
  ];

  const stayActivities = [
    {place:'Stadtkyll',title:'Kurpark Stadtkyll',text:'Ruhiger Spaziergang durch den Park an der Kyll – ideal für eine unkomplizierte erste Runde nach der Ankunft.',image:'https://www.eifel.info/images/f4uJBKVpLVw/rs:fill:1400:788/cb:/g:ce/aHR0cHM6Ly9yZXNjLmRlc2tsaW5lLm5ldC9pbWFnZXMvUlBULzEvODk3N2M3ZTItMTQ2ZS00NzE2LThlZmItZTg4OGExY2NjNTBiLzk5L2ltYWdlLmpwZw',url:'https://www.eifel.info/pois/kurpark-stadtkyll',tag:'Spaziergang'},
    {place:'Wirfttal',title:'Minigolf Landal Wirfttal',text:'Kompakte Familienrunde im Ferienpark – gut für einen lockeren Nachmittag ohne lange Planung.',image:'https://www.eifel.info/images/BtwGtFbMwEk/rs:fill:1400:788/cb:/g:ce/aHR0cHM6Ly9yZXNjLmRlc2tsaW5lLm5ldC9pbWFnZXMvUlBULzEvMTI5YTNiMDEtODI3Mi00NTkxLTllMTEtNDkxNjkxYzc1YmI4Lzk5L2ltYWdlLmpwZw',url:'https://www.eifel.info/pois/minigolf-landal-wirfttal',tag:'Familie'},
    {place:'Wirfttal',title:'Angeln am Wirftstausee',text:'Ruhige Stunden am Wasser mit Waldkulisse. Vor dem Angeln bitte die aktuellen Voraussetzungen und Tageskarten prüfen.',image:'https://www.eifel.info/images/YaVUJQQtO1E/rs:fill:1400:788/cb:/g:ce/aHR0cHM6Ly9yZXNjLmRlc2tsaW5lLm5ldC9pbWFnZXMvUlBULzEvNWFiNWVmZTAtMTk4ZS00MWQ1LTk4YmMtMWEyMWM0YWRkYzkzLzk5L2ltYWdlLmpwZWc',url:'https://www.eifel.info/pois/angeln-am-stausee-wirfttal',tag:'Am Wasser'},
    {place:'Kronenburg',title:'Kronenburger See',text:'Seeufer, Wasserblick und Sommermomente in wenigen Fahrminuten Entfernung.',image:'https://www.eifel.info/images/FJHkRY2rGxo/rs:fill:1400:788/cb:/g:ce/aHR0cHM6Ly9yZXNjLmRlc2tsaW5lLm5ldC9pbWFnZXMvUlBULzEvYWExY2Q1NzktMDA4MS00NTVjLTgyNzQtMDM1ZWM5Zjk3ZTE5Lzk5L2ltYWdlLmpwZw',url:'https://www.eifel.info/en/pois/angeln-am-kronenburger-see',tag:'See'},
    {place:'Kronenburg',title:'Burgort Kronenburg',text:'Historischer Ortskern mit Burgruine, Fachwerk, kleinen Gassen und weitem Blick über die Eifellandschaft.',image:'https://www.eifel.info/images/jfIFm08HktU/rs:fill:1400:788/cb:/g:ce/aHR0cHM6Ly9yZXNjLmRlc2tsaW5lLm5ldC9pbWFnZXMvUlBULzEvZGVhMGE3NWQtZjVmNi00NTc1LThjOTctYjZhZWQ2YThkNDEwLzk5L2ltYWdlLmpwZw',url:'https://www.eifel.info/pois/kronenburg',tag:'Historisch'},
    {place:'Steffeln',title:'Eichholzmaar',text:'Kleines Vulkanmaar mit Rundweg, viel Ruhe und einem sehr typischen Landschaftsgefühl der Vulkaneifel.',image:'https://www.eifel.info/images/ILqDxkXHt9w/rs:fill:1400:788/cb:/g:ce/aHR0cHM6Ly9yZXNjLmRlc2tsaW5lLm5ldC9pbWFnZXMvUlBULzEvOGE4OTNmM2EtNDU2Zi00NDIyLTg0NjgtOWY4NzU5ZjczMjYwLzk5L2ltYWdlLmpwZw',url:'https://www.eifel.info/pois/eichholzmaar',tag:'Vulkaneifel'},
    {place:'Gerolstein',title:'Gerolsteiner Dolomiten',text:'Markante Felsen, Aussichtspunkte und eine der charakteristischen Wanderkulissen rund um Gerolstein.',image:'https://www.eifel.info/images/o8TRP61yGkM/rs:fill:1400:788/cb:/g:ce/aHR0cHM6Ly9yZXNjLmRlc2tsaW5lLm5ldC9pbWFnZXMvUlBULzEvM2U1NWVkZmYtZGY0My00YjQ0LWEwNmYtNDIwMWJjNzBiMDE5Lzk5L2ltYWdlLmpwZw',url:'https://www.eifel.info/pois/gerolsteiner-dolomiten',tag:'Wandern'},
    {place:'Pelm',title:'Adler- und Wolfspark Kasselburg',text:'Greifvögel, Wolfsrudel und die Kasselburg – ein großes Ausflugsziel besonders für Familien.',image:'https://www.eifel.info/images/EBu8tgFAmAU/rs:fill:1400:788/cb:/g:ce/aHR0cHM6Ly9yZXNjLmRlc2tsaW5lLm5ldC9pbWFnZXMvUlBULzEvMWJhMmM0OTEtMzk2Mi00NjFjLWFlYmUtY2I3M2VkMjA1M2MxLzk5L2ltYWdlLmpwZw',url:'https://www.eifel.info/pois/adler-und-wolfspark-kasselburg',tag:'Familie'}
  ];

  const byText=(selector,text)=>[...document.querySelectorAll(selector)].find(el=>el.textContent.trim()===text);
  const esc=value=>String(value??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;');

  function patchGuide(){
    if(typeof guideItems!=='undefined')guideItems.splice(0,guideItems.length,...verifiedGuideItems);
    const allFilter=document.querySelector('[data-guide-filter="all"]');if(allFilter)allFilter.textContent='Alle Tipps';
    if(typeof renderRecommendations==='function')renderRecommendations();if(typeof renderGuide==='function')renderGuide();
    const guideView=document.querySelector('[data-view="guide"]');
    if(guideView&&!guideView.querySelector('.verified-note')){
      const note=document.createElement('p');note.className='verified-note';note.textContent=`Lokale Angaben geprüft am ${VERIFIED_AT}. Öffnungszeiten können sich kurzfristig ändern – vor der Abfahrt bitte die verlinkte Quelle prüfen.`;guideView.querySelector('#guideGrid')?.insertAdjacentElement('afterend',note);
    }
  }

  function experienceCard(item){
    return `<a class="stay-experience-card" href="${esc(item.url)}" target="_blank" rel="noreferrer"><div class="stay-experience-media"><img src="${esc(item.image)}" alt="" loading="lazy" decoding="async"></div><div class="stay-experience-copy"><small>${esc(item.place)} · ${esc(item.tag)}</small><h3>${esc(item.title)}</h3><p>${esc(item.text)}</p><span class="stay-experience-link">mehr erfahren <b>↗</b></span></div></a>`;
  }

  function experienceRail(id,title,items){
    return `<section class="stay-experience-group"><div class="stay-experience-head"><div><span class="card-label">Entdecken</span><h2>${esc(title)}</h2></div><div class="stay-experience-controls"><button type="button" data-stay-scroll="${id}" data-direction="-1" aria-label="Zurück">‹</button><button type="button" data-stay-scroll="${id}" data-direction="1" aria-label="Weiter">›</button></div></div><div class="stay-experience-rail" id="${id}" tabindex="0">${items.map(experienceCard).join('')}</div><div class="stay-experience-progress" data-progress-for="${id}" aria-hidden="true">${items.map((_,i)=>`<i${i===0?' class="active"':''}></i>`).join('')}</div></section>`;
  }

  function updateRailProgress(rail){
    const progress=document.querySelector(`[data-progress-for="${rail.id}"]`);if(!progress)return;
    const cards=[...rail.querySelectorAll('.stay-experience-card')];if(!cards.length)return;
    const left=rail.scrollLeft;let active=0;let best=Infinity;
    cards.forEach((card,index)=>{const distance=Math.abs(card.offsetLeft-left);if(distance<best){best=distance;active=index;}});
    [...progress.children].forEach((item,index)=>item.classList.toggle('active',index===active));
  }

  function bindSwipeRail(rail){
    let dragging=false,startX=0,startLeft=0,moved=false;
    const stop=()=>{if(!dragging)return;dragging=false;rail.classList.remove('is-dragging');};
    rail.addEventListener('pointerdown',event=>{if(event.pointerType==='mouse'&&event.button!==0)return;dragging=true;moved=false;startX=event.clientX;startLeft=rail.scrollLeft;rail.classList.add('is-dragging');rail.setPointerCapture?.(event.pointerId);});
    rail.addEventListener('pointermove',event=>{if(!dragging)return;const delta=event.clientX-startX;if(Math.abs(delta)>6)moved=true;rail.scrollLeft=startLeft-delta;});
    rail.addEventListener('pointerup',stop);rail.addEventListener('pointercancel',stop);rail.addEventListener('lostpointercapture',stop);
    rail.addEventListener('click',event=>{if(moved){event.preventDefault();event.stopPropagation();moved=false;}},true);
    let raf=0;rail.addEventListener('scroll',()=>{cancelAnimationFrame(raf);raf=requestAnimationFrame(()=>updateRailProgress(rail));},{passive:true});
    updateRailProgress(rail);
  }

  function patchStayExperiences(stay){
    if(!stay||document.querySelector('#stayExperiences'))return;const timeline=stay.querySelector('.timeline');if(!timeline)return;
    const hub=document.createElement('section');hub.id='stayExperiences';hub.className='content-section stay-experiences';
    hub.innerHTML=`<div class="stay-experiences-intro"><div><span class="card-label">Waldhaus Auswahl</span><h2>Genießen & erleben.</h2><p>Die bewährten Empfehlungen aus dem ursprünglichen Waldhaus – jetzt wieder als bildstarkes Erlebnis-Caroussel.</p></div><button class="text-link" id="stayMoreTips" type="button">Alle weiteren Tipps →</button></div>${experienceRail('stayDiningRail','Essen & Trinken',stayDining)}${experienceRail('stayActivityRail','Aktivitäten',stayActivities)}<p class="stay-experience-note">Mit den Pfeilen, per Maus-Drag oder auf Handy und Tablet direkt per Swipe bedienen. Öffnungszeiten und Saisonbetrieb bitte vor der Abfahrt über den jeweiligen Link prüfen.</p>`;
    timeline.insertAdjacentElement('afterend',hub);
    hub.querySelectorAll('.stay-experience-rail').forEach(bindSwipeRail);
    hub.querySelectorAll('[data-stay-scroll]').forEach(button=>button.addEventListener('click',()=>{const rail=document.getElementById(button.dataset.stayScroll);if(!rail)return;const card=rail.querySelector('.stay-experience-card');const step=(card?.getBoundingClientRect().width||300)+16;rail.scrollBy({left:(Number(button.dataset.direction)||1)*step,behavior:'smooth'});}));
    hub.querySelector('#stayMoreTips')?.addEventListener('click',()=>{if(typeof navigate==='function')navigate('guide');});
    hub.querySelectorAll('.stay-experience-media img').forEach(img=>img.addEventListener('error',()=>img.closest('.stay-experience-card')?.classList.add('image-missing'),{once:true}));
  }

  function patchStay(){
    const stay=document.querySelector('[data-view="stay"]');if(!stay)return;const info=stay.querySelector('.info-grid');if(info)info.innerHTML='<div><small>Adresse</small><strong>Killerberg 2 · 54589 Kerschenbach</strong></div><div><small>Parken</small><strong>PKW-Parkplatz vorhanden</strong></div><div><small>Zugang</small><strong>Mit Schlüssel · Details vor Anreise</strong></div><div><small>Check-in</small><strong>ab 15:00 Uhr</strong></div>';
    const route=stay.querySelector('a[href*="google.com/maps"]');if(route)route.href='https://www.google.com/maps/search/?api=1&query=Killerberg%202%2C%2054589%20Kerschenbach';const badge=stay.querySelector('.stay-badge');if(badge)badge.querySelector('strong').textContent='15:00';
    const timeline=stay.querySelector('.timeline');if(timeline&&!document.querySelector('#guestContribution')){const article=document.createElement('article');article.id='guestContribution';article.className='timeline-card';article.innerHTML='<div class="timeline-time">Gut zu wissen</div><div class="timeline-dot"></div><div class="timeline-body"><span class="card-label">Gästebeitrag</span><h2>Aktuell 0,75 € pro Person & Nacht.</h2><p>Der einheitliche Gästebeitrag der Verbandsgemeinde Gerolstein gilt für beitragspflichtige Übernachtungsgäste. Kinder unter 6 Jahren sowie Geschäfts- und Bildungsreisende sind befreit.</p><a class="text-link" href="https://www.gerolstein.de/buergerservice/leistungen/RLP%3Aentry%3A5272537%3AANLR-VLR/gaestebeitrag-in-der-verbandsgemeinde-gerolstein-gaestekarte-vorteilsleistungen-und-meldesystem/" target="_blank" rel="noreferrer">Offizielle Information ↗</a></div>';timeline.appendChild(article);}patchStayExperiences(stay);
  }

  function patchHouse(){
    const house=document.querySelector('[data-view="house"]');if(!house)return;const heroCopy=house.querySelector('.page-hero p');if(heroCopy)heroCopy.textContent='Die wichtigsten Informationen zum Waldhaus, zur Ausstattung und für den Aufenthalt – kurz und griffbereit.';const status=house.querySelector('.house-status');if(status){status.querySelector('strong').textContent='Hausinfos geprüft';status.querySelector('small').textContent=`Stand · ${VERIFIED_AT}`;}
    const wifi=house.querySelector('.house-card.featured');if(wifi){wifi.querySelector('small').textContent='WLAN';wifi.querySelector('h2').textContent='Kostenloses WLAN';wifi.querySelector('p').innerHTML='Zugangsdaten erhaltet ihr mit den Anreiseinformationen.';const copy=wifi.querySelector('#copyWifi');if(copy){copy.hidden=true;copy.disabled=true;}}const wlanQuick=byText('.quick-card strong','WLAN')?.closest('.quick-card');if(wlanQuick)wlanQuick.querySelector('small').textContent='Kostenlos vorhanden';
    const fireplace=byText('.house-card h2','Kamin')?.closest('.house-card');if(fireplace){fireplace.querySelector('small').textContent='Draußen';fireplace.querySelector('h2').textContent='Garten, Terrasse & Grill';fireplace.querySelector('p').textContent='Eigener Garten, Terrasse und Grillmöglichkeit.';const button=fireplace.querySelector('[data-sheet]');if(button){button.dataset.sheet='outdoor';button.textContent='Details →';}}const fireQuick=byText('.quick-card strong','Kamin')?.closest('.quick-card');if(fireQuick){fireQuick.querySelector('strong').textContent='Draußen';fireQuick.querySelector('small').textContent='Garten, Terrasse & Grill';}
    if(typeof sheetContent!=='undefined'){sheetContent.outdoor={label:'Draußen',title:'Garten, Terrasse & Grill',html:'<p>Zum Waldhaus gehören ein eigener Garten, eine Terrasse und eine Grillmöglichkeit. Bitte den Grill nur beaufsichtigt nutzen und vor dem Verlassen vollständig löschen beziehungsweise abkühlen lassen.</p>'};sheetContent.appliances={label:'Küche',title:'Küche & Geräte',html:'<p>Die öffentlich beschriebenen Ausstattungsmerkmale umfassen eine Küche mit Kühlschrank, Backofen, Kaffeemaschine, Wasserkocher und Toaster sowie TV/Satelliten-TV.</p>'};sheetContent.emergency={label:'Wichtig',title:'Notfall & Kontakte',html:'<p><strong>Akuter Notfall:</strong> 112</p><p><strong>Ärztlicher Bereitschaftsdienst:</strong> 116117</p><p><strong>Gastgeber-Kontakt:</strong> +49 171 4421800</p><p><strong>Marien-Apotheke Stadtkyll:</strong> +49 6597 2319</p><p>Bei einem Problem am Haus bitte zuerst den Gastgeber-Kontakt nutzen, sofern kein akuter medizinischer oder sonstiger Notfall vorliegt.</p>'};}
    const grid=house.querySelector('.house-grid');if(grid&&!document.querySelector('#verifiedHouseFacts')){const section=document.createElement('section');section.id='verifiedHouseFacts';section.className='content-section welcome-grid verified-facts';section.innerHTML='<article class="card"><span class="card-label">Das Waldhaus</span><h2>80 m² für bis zu 4 Gäste.</h2><div class="info-grid verified-info"><div><small>Schlafen</small><strong>2 Schlafzimmer</strong></div><div><small>Bad</small><strong>1 Bad mit Dusche/WC</strong></div><div><small>Haustiere</small><strong>willkommen</strong></div><div><small>Hausregel</small><strong>Nichtraucher</strong></div></div><p class="verified-copy">Nurdach-Ferienhaus mit Wohn-/Essbereich, Küche, Terrasse und eigenem Garten.</p></article><article class="card equipment-card"><span class="card-label">Ausstattung & Lage</span><h2>Ruhig – und gut ausgestattet.</h2><span class="fact-subhead">Ausstattung</span><div class="equipment-overview"><span><small>WLAN</small><strong>kostenlos</strong></span><span><small>Parken</small><strong>PKW-Stellplatz</strong></span><span><small>TV</small><strong>Satelliten-TV</strong></span><span><small>Draußen</small><strong>Terrasse & Garten</strong></span><span><small>Küche</small><strong>Kühlschrank & Backofen</strong></span><span><small>Grill</small><strong>vorhanden</strong></span></div><p class="equipment-detail">Außerdem vorhanden: Kaffeemaschine, Wasserkocher und Toaster.</p><span class="fact-subhead location-subhead">Direkt in der Umgebung</span><div class="info-grid verified-info location-grid"><div><small>Wanderweg</small><strong>ca. 50 m</strong></div><div><small>Wald</small><strong>ca. 100 m</strong></div><div><small>Radweg</small><strong>ca. 700 m</strong></div><div><small>Zentrum</small><strong>ca. 1,5 km</strong></div></div></article>';grid.insertAdjacentElement('afterend',section);}
  }

  function patchCheckout(){if(typeof checkoutItems!=='undefined'){const fire=checkoutItems.findIndex(item=>item[0]==='fire');if(fire>=0)checkoutItems[fire]=['fire','Außenbereich prüfen','Grill vollständig aus bzw. abgekühlt, Terrasse ordentlich hinterlassen.'];const key=checkoutItems.findIndex(item=>item[0]==='key');if(key>=0)checkoutItems[key]=['key','Schlüssel zurückgeben','Schlüssel nach den vereinbarten Abreisehinweisen zurückgeben.'];if(typeof renderCheckout==='function')renderCheckout();}const side=document.querySelector('.checkout-side');if(side){const h2=side.querySelector('h2');if(h2)h2.textContent='Bis 10:00 Uhr';const p=side.querySelector('p');if(p)p.textContent='Bitte das Haus bis 10:00 Uhr verlassen und den Schlüssel nach den vereinbarten Abreisehinweisen zurückgeben.';}}
  function patchHome(){const next=document.querySelector('.next-card');if(next){const p=next.querySelector('p');if(p)p.textContent='Adresse, Parkplatz, Check-in und die wichtigsten Hausinfos sind für euch gebündelt.';const list=next.querySelector('.mini-list');if(list)list.innerHTML='<span><b>15:00</b> Check-in</span><span><b>10:00</b> Check-out</span><span><b>1,5 km</b> bis Stadtkyll-Zentrum</span>';}}

  function addStyles(){
    if(document.querySelector('#verifiedContentStyles'))return;const style=document.createElement('style');style.id='verifiedContentStyles';style.textContent=`
      :root{--bg:#14251d;--bg-soft:#1d3327;--surface:rgba(246,239,221,.095);--surface-strong:rgba(246,239,221,.15);--surface-light:#f2ead9;--text:#fbf5e8;--muted:#c1c9bd;--ink:#1a261f;--accent:#d7b56d;--accent-strong:#efd39a;--accent-ink:#302611;--warm:#e2b667;--line:rgba(246,235,211,.18);--shadow:0 28px 80px rgba(4,12,8,.25)}
      html,body{background:#14251d}body{background:radial-gradient(circle at 84% 9%,rgba(214,181,109,.09),transparent 32rem),radial-gradient(circle at 10% 42%,rgba(105,151,124,.12),transparent 36rem),var(--bg)}.ambient span{opacity:.12}.topbar{background:rgba(20,37,29,.84);border-color:rgba(239,211,154,.18);box-shadow:0 14px 38px rgba(4,12,8,.13)}.desktop-nav{background:rgba(255,248,232,.055)}.nav-item:hover,.nav-item.is-active{background:rgba(239,211,154,.11)}.hero-shade{background:linear-gradient(180deg,rgba(7,17,12,.20),rgba(7,17,12,.03) 38%,rgba(12,25,18,.62) 78%,rgba(12,25,18,.84))}.card,.quick-card,.timeline-card,.house-card,.checkout-side{box-shadow:0 18px 50px rgba(4,12,8,.12)}
      .verified-note{max-width:1100px;margin:.7rem auto 0;padding:0 1.25rem 1.4rem;color:var(--muted);font-size:.76rem;line-height:1.5}.verified-facts{margin-top:1rem}.verified-info{margin-top:1rem}.verified-copy{margin-top:1rem;color:var(--muted)}.verified-facts .card{min-height:100%}
      .stay-experiences{padding:1.2rem 0 2.8rem}.stay-experiences-intro{display:flex;align-items:end;justify-content:space-between;gap:1.25rem;padding:1rem 4px .3rem}.stay-experiences-intro>div{max-width:760px}.stay-experiences-intro h2{margin:.35rem 0 .45rem;font-family:Georgia,serif;font-weight:400;font-size:clamp(32px,4vw,52px)}.stay-experiences-intro p{margin:0;color:var(--muted);line-height:1.6}.stay-experience-group{margin-top:1.4rem;padding:clamp(20px,2.5vw,32px);border:1px solid rgba(239,211,154,.24);border-radius:26px;background:linear-gradient(125deg,rgba(50,79,65,.78),rgba(72,75,49,.58));box-shadow:0 24px 65px rgba(4,12,8,.15);backdrop-filter:blur(18px)}.stay-experience-head{display:flex;align-items:center;justify-content:space-between;gap:1.25rem;margin-bottom:1rem}.stay-experience-head h2{margin:.35rem 0 0;font-size:clamp(28px,3vw,42px);font-weight:750;letter-spacing:-.025em}.stay-experience-head .card-label{color:var(--warm)}.stay-experience-controls{display:flex;gap:.7rem}.stay-experience-controls button{width:3.05rem;height:3.05rem;border-radius:12px;border:1px solid rgba(249,238,213,.22);background:rgba(249,238,213,.085);color:var(--text);font:inherit;font-size:1.55rem;font-weight:800;cursor:pointer;transition:.2s ease}.stay-experience-controls button:hover{transform:translateY(-2px);background:rgba(249,238,213,.14);border-color:rgba(239,211,154,.45)}
      .stay-experience-rail{display:grid;grid-auto-flow:column;grid-auto-columns:calc((100% - 3rem)/4);gap:1rem;overflow-x:auto;scroll-snap-type:x mandatory;scroll-behavior:smooth;overscroll-behavior-inline:contain;-webkit-overflow-scrolling:touch;scrollbar-width:none;padding:.35rem .1rem .75rem;cursor:grab;user-select:none}.stay-experience-rail::-webkit-scrollbar{display:none}.stay-experience-rail.is-dragging{cursor:grabbing;scroll-snap-type:none}.stay-experience-card{position:relative;scroll-snap-align:start;min-height:390px;border-radius:16px;overflow:hidden;text-decoration:none;color:#fffaf0;background:#1d2c24;border:1px solid rgba(255,248,232,.17);box-shadow:0 18px 44px rgba(5,12,8,.18);transform:translateZ(0);transition:transform .28s ease,border-color .22s ease,box-shadow .28s ease}.stay-experience-card:hover{transform:translateY(-5px);border-color:rgba(239,211,154,.48);box-shadow:0 28px 62px rgba(5,12,8,.28)}.stay-experience-media{position:absolute;inset:0;overflow:hidden;background:linear-gradient(135deg,#516953,#22342a)}.stay-experience-media img{width:100%;height:100%;object-fit:cover;display:block;pointer-events:none;transition:transform .4s ease,filter .3s ease;filter:saturate(1.03) brightness(1.04)}.stay-experience-card:hover .stay-experience-media img{transform:scale(1.045);filter:saturate(1.08) brightness(1.06)}.stay-experience-card.image-missing .stay-experience-media img{display:none}.stay-experience-card:after{content:'';position:absolute;inset:0;background:linear-gradient(180deg,rgba(5,11,8,.02) 14%,rgba(5,11,8,.12) 45%,rgba(5,11,8,.82) 78%,rgba(5,11,8,.94));pointer-events:none}.stay-experience-copy{position:absolute;z-index:2;left:0;right:0;bottom:0;padding:1.2rem 1.25rem 1.3rem}.stay-experience-copy small{display:block;color:#f3c96f;font-size:.72rem;font-weight:900;letter-spacing:.075em;text-transform:uppercase}.stay-experience-copy h3{margin:.42rem 0 .42rem;font-size:clamp(1.2rem,1.5vw,1.55rem);line-height:1.08}.stay-experience-copy p{margin:0;color:rgba(255,250,240,.82);font-size:.86rem;line-height:1.46;display:-webkit-box;-webkit-line-clamp:3;-webkit-box-orient:vertical;overflow:hidden}.stay-experience-link{display:inline-flex;align-items:center;gap:.55rem;margin-top:1rem;padding:.62rem .92rem;border:1px solid rgba(255,250,240,.34);border-radius:999px;background:rgba(255,250,240,.13);backdrop-filter:blur(9px);font-size:.78rem;font-weight:900}.stay-experience-link b{font-size:.9rem}.stay-experience-progress{display:flex;gap:.55rem;margin-top:.6rem}.stay-experience-progress i{display:block;width:36px;height:4px;border-radius:999px;background:rgba(255,248,232,.18);transition:width .2s ease,background .2s ease}.stay-experience-progress i.active{width:54px;background:var(--warm)}.stay-experience-note{margin:1rem .15rem 0;color:var(--muted);font-size:.72rem;line-height:1.5}
      @media(max-width:1050px){.stay-experience-rail{grid-auto-columns:calc((100% - 1rem)/2.25)}}
      @media(max-width:700px){:root{--bg:#172b21;--bg-soft:#20382b}.stay-experiences{padding-top:.4rem}.stay-experiences-intro{display:block}.stay-experiences-intro .text-link{margin-top:.8rem}.stay-experience-group{padding:18px 14px;border-radius:22px}.stay-experience-head{align-items:flex-end}.stay-experience-head h2{font-size:29px}.stay-experience-controls button{width:2.55rem;height:2.55rem}.stay-experience-rail{grid-auto-columns:86%;gap:.8rem;margin-right:-.35rem;padding-right:1rem}.stay-experience-card{min-height:405px}.stay-experience-copy{padding:1rem}.stay-experience-copy h3{font-size:1.28rem}.stay-experience-progress i{width:24px}.stay-experience-progress i.active{width:38px}}
      @media(prefers-reduced-motion:reduce){.stay-experience-card,.stay-experience-media img,.stay-experience-controls button,.stay-experience-progress i{transition:none!important}.stay-experience-rail{scroll-behavior:auto}}
    `;document.head.appendChild(style);
  }

  function apply(){addStyles();patchGuide();patchHome();patchStay();patchHouse();patchCheckout();}
  const run=()=>setTimeout(apply,60);document.readyState==='loading'?document.addEventListener('DOMContentLoaded',run,{once:true}):run();
})();
